import { notFound } from 'next/navigation'
import bundle from '../../../../public/data/institutional-map/bundle.json'
import type { Bundle, ResearchRecord } from '../../../lib/institutional-map-types'
import styles from '../../../components/institutional-evidence.module.css'
const data=bundle as unknown as Bundle
export function generateStaticParams(){return data.relationships.map(r=>({relationshipId:r.id}))}
export default async function RelationshipEvidence({params}:{params:Promise<{locale:string;relationshipId:string}>}){
 const {locale,relationshipId}=await params;const r=data.relationships.find(x=>x.id===relationshipId);if(!r)notFound()
 const prefix=locale==='en'?'':`/${locale}`;const source=data.institutions.find(i=>i.id===r.source);const target=data.institutions.find(i=>i.id===r.target)
 const instrument=data.instruments.find(i=>i.id===r.instrumentId);const type=data['relation-types'].find(t=>t.id===r.type)
 const analyses=data['analytical-relations'].filter(a=>a.relationshipIds.includes(r.id));const attrs=data['institution-attributes'].filter(a=>analyses.some(x=>x.attributeIds.includes(a.id)))
 const evidenceIds=new Set([...(r.evidenceIds??[]),...(r.counterEvidenceIds??[]),...analyses.flatMap(a=>[...a.evidenceIds,...a.counterEvidenceIds,...a.conditions.flatMap((c:any)=>c.evidenceIds)]),...attrs.flatMap(a=>[...a.evidenceIds,...a.counterEvidenceIds])])
 const evidence=data.evidence.filter(e=>evidenceIds.has(e.id));const check=data['status-checks'].find(s=>s.id===r.statusCheckId)
 const keys=new Set([`relationships/${r.id}`,`instruments/${r.instrumentId}`,...evidence.map(e=>`evidence/${e.id}`),...attrs.map(a=>`institution-attributes/${a.id}`),...analyses.map(a=>`analytical-relations/${a.id}`)])
 const item=(e:ResearchRecord)=>{const s=data.sources.find(s=>s.id===e.sourceId)!;const version=data['source-versions']?.find(v=>v.sourceId===s.id);return <section key={e.id} id={e.id} className={styles.record}><h3>{e.claim}</h3><dl><dt>Source</dt><dd><a href={s.url}>{s.title}</a> · {s.publisher}</dd><dt>Version</dt><dd>{e.sourceVersion}; retrieved {s.accessedOn}</dd><dt>Exact locator</dt><dd>{e.locator}</dd><dt>Limit</dt><dd>{e.limitation}</dd></dl>{version?.sha256?<p className={styles.hash}>Retrieved bytes SHA-256: {version.sha256}</p>:<p className={styles.meta}>Byte capture unavailable. {version?.failure} Published document identity and locator remain recorded.</p>}</section>}
 return <article className={styles.page}>
 <a href={`${prefix}/institutional-links`}>← Evidence & methodology</a><h1>{source?.label} {r.directed?'→':'↔'} {target?.label}</h1>
 <p className={styles.meta}>{data.release.version} · Evidence cutoff 12 September 2026</p><p className={styles.badge}>Directly documented interface</p><h2>{type?.label}</h2><p>{type?.definition}</p><p>{type?.direction}. {r.rationale}</p>
 <p className={styles.lineage}>Displayed claim → analysis (if present) → coded attributes → interface / instrument → atomic evidence → source version</p>
 <h2>Instrument and timeline</h2><dl><dt>Instrument</dt><dd>{instrument?.label}</dd><dt>Bindingness</dt><dd>{instrument?.bindingness}</dd><dt>Announced</dt><dd>{r.announcedOn??'Unknown'}</dd><dt>Observed by</dt><dd>{r.observedBy??'Unknown'} · {r.datePrecision}</dd><dt>Effective period</dt><dd>{r.effectiveFrom??'Unknown'} → {r.effectiveTo??'Unknown'}</dd><dt>Event</dt><dd>{r.eventStatus}</dd><dt>Status at cutoff</dt><dd>{r.currentStatus}</dd><dt>Last confirmation</dt><dd>{check?.lastConfirmedOn??'Unknown'}</dd></dl>
 <p>{r.conflictDisposition}</p><ul>{r.limitations.map((x:string)=><li key={x}>{x}</li>)}</ul>
 <h2>Status investigation</h2><p>Checked {check?.checkedOn}; assessed as of {check?.asOf}. Last confirmation does not establish uninterrupted continuity.</p><dl>{Object.entries(check?.checks??{}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl><details><summary>Search queries</summary><ul>{check?.queries.map((q:string)=><li key={q}>{q}</li>)}</ul></details>
 <h2 id="analysis">Analytical assessment</h2>{analyses.length?analyses.map(a=>{const rubric=data['analytical-rubrics'].find(x=>x.id===a.type);return <section key={a.id} className={styles.record}><h3>{rubric?.label}</h3><p className={styles.badge}>Reviewed analytical assessment</p><p>{a.assessment}</p><p>{rubric?.definition}</p><p>Derivation rule: {rubric?.rule}</p><p>{a.derivation}</p><ul>{a.conditions.map((c:any)=><li key={c.id}>{c.id}: {c.met?'established':'unresolved'}. {c.reason} {c.evidenceIds.map((id:string)=><a href={`#${id}`} key={id}>Evidence: {id} </a>)}</li>)}</ul><p>Necessary conditions: {a.necessityMet?'met':'not all established'}. Sufficient conditions: {a.sufficiencyMet?'met':'not established'}.</p><ul>{a.limitations.map((l:string)=><li key={l}>{l}</li>)}</ul></section>}):<p>No reviewed analytical conclusion is attached. This does not establish independence or absence of an institutional constraint.</p>}
 <h2>Coded attributes</h2>{attrs.map(a=>{const rubric=data['attribute-rubrics'].find(x=>x.id===a.rubricId);return <section key={a.id} className={styles.record}><h3>{rubric?.id}: {a.value}</h3><p>{rubric?.definition}</p><p>{rubric?.unit}. {a.context}; assessed {a.assessedOn}.</p><p>{a.reasoning}</p><details><summary>Published rubric anchors</summary><dl>{rubric?.anchors.map((x:any)=><div key={x.id}><dt>{x.id}</dt><dd>{x.definition}</dd></div>)}</dl><p>{rubric?.uncertaintyRule}</p></details></section>})}
 <h2>Atomic evidence and exact sources</h2>{evidence.map(item)}
 <h2>Supporting and conflicting evidence</h2><p>Interface support: {r.evidenceIds.join(', ')}. Counterevidence: {r.counterEvidenceIds?.join(', ')||'None recorded; this does not mean none exists.'}</p>{analyses.map(a=><p key={a.id}>Analysis {a.id}: support {a.evidenceIds.join(', ')}; counterevidence {a.counterEvidenceIds.join(', ')||'none recorded'}.</p>)}
 <h2>Substantive review</h2>{data.reviews.filter(x=>keys.has(x.recordKey)).map(v=><div key={v.id} className={styles.record}><p>{v.recordKey}: {v.decision} · {v.reviewerType} reviewer {v.reviewer} · {v.checkedOn}</p><p>{v.disposition}</p><p className={styles.hash}>Approval fingerprint: {v.researchHash}</p></div>)}
 <p><a href={`https://github.com/saykig/Cepheus/blob/${data.release.methodologyCommit}/research/institutional-map/METHODOLOGY.md`}>Release-pinned methodology →</a></p>
 </article>
}
